config/routes.rb
Rails.application.routes.draw do
  resources :news
  devise_for :users
  resources :users
  resources :products do
  resources :comments
  resources :charges
  end
  resources :payments, only: [:create]    
  resources :orders, only: [:index, :show, :new, :create]
  resources :charges

  root 'static_pages#about'
  
  get 'contact' => 'static_pages#contact'

  get 'index' => 'static_pages#index'
  
  get 'landing_page' => 'static_pages#landing_page'

  get 'login' => 'static_pages#login'

  get 'about' => 'static_pages#about'

  get 'signup' => 'users#new'

  post 'static_pages/thank_you'

   

  resources :orders, only: [:index, :show, :new, :create]
end

app/controllers/payments_controller.rb
class ChargesController < ApplicationController
  def new
    # this will remain empty unless you need to set some instance variables to pass on
  end
 
  def create
    # Amount in cents
    amount = params[:stripeAmount].to_i * 100
 
    # Create the customer in Stripe
    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      card: params[:stripeToken]
    )
 
    # Create the charge using the customer data returned by Stripe API
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: amount,
      description: 'Rails Stripe customer',
      currency: 'usd'
    )
 
    # place more code upon successfully creating the charge
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
    flash[:notice] = "Please try again"
  end
end

app/views/payments/_form.html.erb
<div class = "field">
<%= f.label :stripe_token %><br />
<%= f.text_field :stripe_token %>
<%- if @cc_last_4 %>
<div class="field">
<input type="radio" name="saved_card" value="true"/> Saved Card
<input type="radio" name="saved_card" value="false"/> New Card
</div>

<div id="saved_card">
<div class="field">
<label>Saved Card</label>
<input id="saved-number" type="text" disabled="true"
value="&bull;&bull;&bull;" <%= @cc_last_4 %>" />
</div>
</div>
<%- end %>
<div id="new_card">
<div class="field">
<label>Card Number</label>
<input id="card-number" type="text" placeholder="4242 4242 4242 4242" />
</div>
<div class="field">
<label>CV Code</label>
<input id="cvc" type="text" placeholder="123" />
</div>
<div class="field">
<label>Expiry Month</label>
<input id="exp-month" type="text" placeholder="12" />
</div>
<div class="field">
<label>Expiry Year</label>
<input id="exp-year" type="text" placeholder="16" />
</div>
</div>
<div class="field">
<%= f.text_field :amount %>
<%= f.label :amount %><br />
</div>
<div class="field">
<%= f.label :user %><br />
<%= f.text_field :user %>
</div>
<div class="actions">
</div>

app/views/payments/create.html.erb
<p id="notice"><%= notice %></p>
<div class="container txt_ctr" id="payment">
  <%= yield %>
  <h2>Thanks for your order!</h2>
</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Stripe token:</b>
  <%= @payment.stripe_token %>
</p>

<p>
  <b>Amount:</b>
  <%= @payment.amount %>
</p>

<p>
  <b>User:</b>
  <%= @payment.user.email if @payment.user %>
</p>


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>