config/routes.rb
Rails.application.routes.draw do
  resources :news
  devise_for :users
  resources :users
  resources :products do
  resources :comments
  resources :charges
  end
  resources :payments, only: [:create]    
  resources :orders, only: [:index, :show, :new, :create]
  resources :charges

  root 'static_pages#about'
  
  get 'contact' => 'static_pages#contact'

  get 'index' => 'static_pages#index'
  
  get 'landing_page' => 'static_pages#landing_page'

  get 'login' => 'static_pages#login'

  get 'about' => 'static_pages#about'

  get 'signup' => 'users#new'

  post 'static_pages/thank_you'

   

  resources :orders, only: [:index, :show, :new, :create]
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comments
	validates :name, presence: true
#	validates :body, presence: true
#	validates :user, presence: true
#	validates :product, presence: true
#	validates :rating, numericality: { only_integer: true }

	validates :price_in_cents, :numericality => { :greater_than => 0 }

	def average_rating
		comments.average(:rating).to_f
	end
	
	def price_in_cents
		(self.price*100).to_i
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
load_and_authorize_resource 
skip_authorize_resource :only => [:index, :show]
  # GET /products
  # GET /products.json
  def index
    if params[:q]

      search_term = params[:q]
      @products = Product.where("name LIKE ?", "%#{search_term}%")
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params

      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s,:number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <%= will_paginate @comments %>
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %>  <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
            <p><%= "Rating: #{comment.rating}/5" %></p>
                <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
            <% if signed_in? && current_user.admin? %>

                 <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
            </p>
            <p><%= "Rating: #{comment.rating}/5" %></p>
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
        </div> 
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="width:20%">
    <label for="product_name">Name</label><br>
    <input id="product_name" name="product[name]" type="text" />
  </div>
  <div class="field" style="width: 25%">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field" style="width: 25%">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field"style="width: 10%">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
    <div class="field"style="width: 10%">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
<p>Add a Review!</p>
<%= form_for([@product, @product.comments.build], remote: true) do |f| %>
  <p>
    <%= f.label :body, "Comments"%> <br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :rating %><br>
    <%= f.text_field :rating, class: "rating" %>  </p>  
    <div class="rating"></div>
  <p>
     <%= f.submit "Submit" %>
  </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= product.description %></td>
  <td><%= image_tag(product.image_url, class:"img-responsive img-product", alt: "image not found" ) %></td>
  <td><%= product.colour %></td>
  <td><%= product.price %></td>
  <td><%= link_to 'Show', product %></td>
  <td><%= link_to 'Edit', edit_product_path(product) %></td>
  <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/products/_product_reviews.html.erb
<div class="product-reviews">
    <%= will_paginate @comments %>
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %>  <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
            <% if signed_in? && current_user.admin? %>

                 <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
            </p>
            
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>

app/views/products/_product_reviews.htmlOLD.erb
<div class="product-reviews">
    <%= will_paginate @comments %>
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %>  <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
            <p><%= "Rating: #{comment.rating}/5" %></p>
            <p><%= comment.body %></p>
            <% if signed_in? && current_user.admin? %>

                 <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
            </p>
            
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>

app/views/products/edit.html.erb
<div class="container">
  <div class="row">
    <div class="md-col-8 xs-col-10 col-centered">
			<h1>Editing Product</h1>

			<%= render 'form' %>

			<%= link_to 'Show', @product %> |
			<%= link_to 'Back', products_path %>
		</div>
  </div>
</div>

app/views/products/index.html.erb
<div class="product-index">
  <% cache (cache_key_for_products) do %>
  <h1>List of Products</h1>

<div class="table-responsive">
  <table class="product-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Image</th>
        <th>Color</th>
        <th>Price</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%= render @products %>
      <% end %>
    </tbody>
      <% cache(p) do |p| %>
      <% end %>      
  </table>


  <br>

  <%= link_to 'New Product', new_product_path %>

</div>

app/views/products/new.html.erb
<div class="container">
  <div class="row">
    <div class="md-col-8 xs-col-10 col-centered">
		<% if signed_in? && current_user.admin? %>
	   	<h1>New Product</h1>
			<%= render 'form' %>

			<%= link_to 'Back', products_path %>
		</div>
  </div>
</div>
    <% end %>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <p>
      <strong><%= @product.name %></strong>
    </p>
    <p>
      <%= @product.description %>
    </p>
    <p>
      Color: <%= @product.colour %>
    </p>
    <p>
    <%= image_tag @product.image_url %>
    </p>
    <p>
      $<%= @product.price %>
  </p>
<br>
    <p>
      <strong>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div></strong></p>

<%= render 'new_comment' %>
<%= render 'comments' %>
<p> <%= will_paginate @comments %></p>


<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $<%= @product.price %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Your Purchase"
          data-amount="<%= @product.price_in_cents %>"></script>
<% end %> 
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
</div>
</div>
</script>
</div>