config/routes.rb
Rails.application.routes.draw do
  resources :news
  devise_for :users
  resources :users
  resources :products do
  resources :comments
  resources :charges
  end
  resources :payments, only: [:create]    
  resources :orders, only: [:index, :show, :new, :create]
  resources :charges

  root 'static_pages#about'
  
  get 'contact' => 'static_pages#contact'

  get 'index' => 'static_pages#index'
  
  get 'landing_page' => 'static_pages#landing_page'

  get 'login' => 'static_pages#login'

  get 'about' => 'static_pages#about'

  get 'signup' => 'users#new'

  post 'static_pages/thank_you'

   

  resources :orders, only: [:index, :show, :new, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quality</title>
  <img src="https://scontent-sea1-1.xx.fbcdn.net/hphotos-ash2/v/t1.0-9/547154_512038738809831_1807830533_n.jpg?oh=71b83f0d7b835d819b21f0ebede3e817&oe=561917E4" alt="Quality Lettering and Graphics" align= "left"; style="width: 15%"; "padding-top: -7em">
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "https://js.stripe.com/v1/" %>
  <%= javascript_include_tag "http://stripe.github.io/jquery.payment/lib/jquery.payment.js" %>
  <%= javascript_tag "Stripe.publishableKey = '#{Rails.configuration.stripe[:publishable_key]}';" %>
  <script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_ebHWWqUGlFUT8MoRRgsHsi04');
  // ...
  </script>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
<!--  <link href="css/zoom.css" rel="stylesheet"> -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<!--  <script src="javascript/zoom.js"></script> -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.1/masonry.pkgd.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.min.js"></script>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="javascript"></script>

</head>

<body style="margin-top: 11em">

<h2 style = "margin-left: 20%">Your Local Source for Signs and Graphics</h2>
<body data-spy="scroll" data-target=".navbar">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
    <!-- Begin Navigation Bar -->

    <nav class="navbar navbar navbar-fixed-top custom-nav" role="navigation" style="background-color: lightgray">


      <div class="container-fluid" style="max-height: 3.5em">    
    
        <div class="nav navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">

            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>  

        <div class="navbar-collapse collapse">
          <div class="row">
          <div class="col-xs-12 col-md-4">
            <ul class="nav navbar-nav navbar-left">
              <li style="font-size:1.8em"><%= link_to 'Quality Lettering', root_path %></li>
            </ul> 
          </div>
          <div class="col-xs-12 col-md-8">
            <ul class="nav navbar-nav navbar-right">
              <li style="font-size:1.2em"><%= link_to 'Home', index_path %></li>
              <li style="font-size:1.2em"><%= link_to 'About', about_path %></li>
              <li style="font-size:1.2em"><%= link_to 'Products', products_path %></li>
              <li style="font-size:1.2em"><%= link_to 'Contact', contact_path %></li>
              <li style="font-size:1.2em"><%= link_to "Users", users_path %></li>
            </ul> 
          </div>
      </div> 
      </div>
      </div> 
      </ul>

      <ul>
      <li style="margin-left: 70%"; list-style-type: "none:>
        <%= form_tag("/products", method: "get") do %>
          <%= text_field_tag(:q) %>
          <%= submit_tag("Product Search") %>
        <% end %>
      </li> 
          <% if user_signed_in? %>
           <li style="margin: 0 5% 0 80%; background-color: red; border-radius: 1em; text-align: center;">
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
          </li>
          <% else %>
          <li style="margin: 0 5% 0 80%; background-color: darkgray; border-radius:  1em; text-align: center;">
          <%= link_to('Login', new_user_session_path)  %>  
          </li>
        <% end %>
        <ul>
    </nav> <!-- End Nav --><hr>
<%= yield %>
<hr>

</body>

</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>

</html>